// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPfhpap7gRTWb9Rn_-wZt0k6KP3gMfY9Q',
    appId: '1:33618813750:web:677fa12e638ea236e00997',
    messagingSenderId: '33618813750',
    projectId: 'gamestore-aede0',
    authDomain: 'gamestore-aede0.firebaseapp.com',
    storageBucket: 'gamestore-aede0.firebasestorage.app',
    measurementId: 'G-RKMWKGG2C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOYILW2BIGbjO1zcgYuneuMXMjnDbRVM',
    appId: '1:33618813750:android:370f8899119188bae00997',
    messagingSenderId: '33618813750',
    projectId: 'gamestore-aede0',
    storageBucket: 'gamestore-aede0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkxiw2ef1JDL_BZB9z3daqRL5RwBwKE8',
    appId: '1:33618813750:ios:4361fbafd8b64066e00997',
    messagingSenderId: '33618813750',
    projectId: 'gamestore-aede0',
    storageBucket: 'gamestore-aede0.firebasestorage.app',
    iosBundleId: 'com.example.gamestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOkxiw2ef1JDL_BZB9z3daqRL5RwBwKE8',
    appId: '1:33618813750:ios:4361fbafd8b64066e00997',
    messagingSenderId: '33618813750',
    projectId: 'gamestore-aede0',
    storageBucket: 'gamestore-aede0.firebasestorage.app',
    iosBundleId: 'com.example.gamestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPfhpap7gRTWb9Rn_-wZt0k6KP3gMfY9Q',
    appId: '1:33618813750:web:6cb48ee70e36cb8ee00997',
    messagingSenderId: '33618813750',
    projectId: 'gamestore-aede0',
    authDomain: 'gamestore-aede0.firebaseapp.com',
    storageBucket: 'gamestore-aede0.firebasestorage.app',
    measurementId: 'G-B6DP4TJJQ8',
  );
}
